### ISSUE TITLE
requests to fake should check for required fields

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-sigs/go-open-service-broker-client#121]
Things like https://github.com/pmorie/go-open-service-broker-client/blob/master/v2/fake/fake.go#L285
should check to make sure that fields required by OSB API https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#body-2 are provided.

I can't think of a reason we'd want to allow a fake to get and respond to an incorrect request.

**Comment by pmorie** [comment]
What behavior are you looking for, exactly?

The original intent was that if you wanted to make assertions on the requests sent to the client, you would use the `Actions` method to get the request and make assertions on it.

**Comment by MHBauer** [comment]
@jberkhahn I think the fake responds with errors now when required fields are not present. This was the issue in one of the recent prs in service-catalog.
