### ISSUE TITLE
18 stale branches in this repo

### ISSUE THREAD

**Issue by mszostok** [kubernetes-sigs/go-open-service-broker-client#155]
**Description**

This repo has 18 stale(3years old) branches which were already merged to the master. IMO we safely delete them.

See: https://github.com/kubernetes-sigs/go-open-service-broker-client/branches/stale

If no one will raise any objection I will delete them on May 29th.

**Comment by MHBauer** [comment]
Go for it. The repo was originally a personal dev environment.

I don't have perms.

**Comment by mszostok** [comment]
all stale branches are deleted
