### ISSUE TITLE
DeprovisionResponse & LastOperationRequest support in broker responses as per OSB spec is missing

### ISSUE THREAD

**Issue by alexwo** [kubernetes-sigs/go-open-service-broker-client#158]
LastOperationResponse and service broker error response fields should be updated to reflect 

The  instance_usable response fields should be included in:
-  UpdateInstanceResponse
-  DeprovisionResponse
-  LastOperationResponse

If an update or deprovisioning operation failed, this flag indicates whether or not the Service Instance is still usable. If true, the Service Instance can still be used, false otherwise. This field MUST NOT be present for errors of other operations. Defaults to true.

update_repeatable  should be available in all update operations.

If an update operation failed, this flag indicates whether this update can be repeated or not. If true, the same update operation MAY be repeated and MAY succeed; if false, repeating the same update operation will fail again. This field MUST NOT be present for errors of other operations. Defaults to true.

**Comment by edwardecook** [comment]
I'm not seeing the `instance_usable` field mentioned in the spec, which version is it in?

**Comment by alexwo** [comment]
it's there in the 2.16 version:
https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md

**Comment by edwardecook** [comment]
Makes sense! It would be good to get this in as part of updating to v2.16, we need to get up to v2.15 first.

**Comment by jhvhs** [comment]
Addressed in #165
