### ISSUE TITLE
Add support for OSBAPI 2.15

### ISSUE THREAD

**Issue by edwardecook** [kubernetes-sigs/go-open-service-broker-client#161]
It would be great to get this client up to date with the current version of the OSBAPI spec (which is now on 2.16). This is an interim step to add support for 2.15.

Below is the list of 2.15 release notes, the plan is to categorise them by whether the work has already been done, work is needed or if it is not relevant to this library.

| Feature | Current Status |
| ------- | -------------- |
| Added a delay to polling response for [Service Instance](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#polling-last-operation-for-service-instances) and [Service Binding](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#polling-last-operation-for-service-bindings) last operations. | WORK REQUIRED |
| Added a Service Offering specific [async polling timeout](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#polling-interval-and-duration). | WORK REQUIRED |
| Allow a Service Instance context to be updated and add [org name, space name, and instance names](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#updating-a-service-instance). | WORK REQUIRED |
| Added list of endpoints to [create Service Binding response body](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#body-9). | WORK REQUIRED |
| Add plan_updateable field to the [Service Plan object](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#service-plan-object).  | WORK REQUIRED |
| Added [maintenance info](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#service-plan-object) support to Service Plans. | WORK REQUIRED |
| Added [request identity header](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#request-identity). | WORK REQUIRED |
| Allow brokers to not return parameters when returning a [Service Instance](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#body-5) or [Service Binding](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#body-5). | N/A |
| Restrict Operation strings to 10,000 chartacters in the response body for [provisioning](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#body-4) or [deprovisioning](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#body-12) a Service Instance, and [binding](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#body-9) or [unbinding](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#body-11) a Service Binding. | N/A |
| Remove character restrictions on names of [Service Offerings](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#service-offering-object), and [Service Plans](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#service-plan-object). | N/A |
| Allow empty descriptions in the response body for getting the last operations of [Service Instances](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#body-1), and [Service Bindings](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#body-2). | N/A |
| Added mechanism for [orphan mitigation](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#orphan-mitigation). | N/A |
| Allow brokers to return 200 for no-op [update Service Instance requests](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#response-5). | N/A |
| [Clarify](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#blocking-operations) what happens when deleting during a provision/bind request. | N/A |
| Clarify broker behavior expected when [deprovisioning while a provision request is in progress](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#deprovisioning) and [unbinding while an unbind request is in progress](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#unbinding). | N/A |
| Clarify broker behavior when a provision request is received [during a provision request for the same instance](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#response-3) or when a binding request is received [during a binding request for the same binding](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#response-6). | N/A |

* `DONE` = Feature is released
* `ALPHA` = implemented behind feature flag
* `WORK REQUIRED` = not currently implemented - requires work
* `N/A` = no changes required to client

For implementation it would probably make sense to follow the same pattern as for 2.14, #144, i.e. PR in features as `Alpha` features and once it is all implemented a final PR to move them out of `Alpha` and add `Version2_15` to the client.

Hopefully that sounds reasonable?

**Comment by jhvhs** [comment]
Status update:

- [x] Added a delay to polling response for Service Instance and Service Binding last operations. | ALPHA #163 
- [ ] Added a Service Offering specific async polling timeout. | WORK REQUIRED
- [ ] Allow a Service Instance context to be updated and add org name, space name, and instance names. | WORK REQUIRED
- [ ] Added list of endpoints to create Service Binding response body. | WORK REQUIRED
- [ ] Add plan_updateable field to the Service Plan object. | WORK REQUIRED
- [ ] Added maintenance info support to Service Plans. | WORK REQUIRED
- [ ] Added request identity header. | WORK REQUIRED

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs.
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
