### ISSUE TITLE
Add Support for OSBAPI 2.16

### ISSUE THREAD

**Issue by jhvhs** [kubernetes-sigs/go-open-service-broker-client#165]
Once the 2.15 support #161 is complete, support for 2.16 has to be added.
Below is a list of items from the relevant release notes:
| Feature | Current status |
| -- | -- |
| Allow Service Brokers to indicate if a Service Instance is still usable after a [failed](https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md#service-broker-errors) update or deprovisioning and if an update can be repeated | WORK REQUIRED |
| Add support for ETag and If-Modified-Since headers in [catalog requests](https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md#catalog-management) | WORK REQUIRED |
| Service Instances can be labelled with information defined by the Service Broker when [provisioned](https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md#provisioning) or [updated](https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md#updating-a-service-instance)| WORK REQUIRED |
| Specify an [expiration timestamp](https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md#binding-6) for the binding | WORK REQUIRED |
| Specify Service ID and Plan ID as hints when retrieving a [service binding](https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md#fetching-a-service-binding) or a [service instance](https://github.com/openservicebrokerapi/servicebroker/blob/v2.16/spec.md#fetching-a-service-instance) | WORK REQUIRED |
| Add guidance of how long the state of an operation SHOULD be remembered | N/A |
| Add guidance to handle 500 errors from Service Instance update | N/A |
| Add guidance to handle requests with invalid data | N/A |
| Specify that Platforms SHOULD NOT reuse IDs | N/A |
| Add CF and K8s annotations to the profile document | N/A |
| Clarify the response code when Platform does not provide the required API version header | N/A |

**Comment by mrbobbytables** [comment]
This project is being archived, closing open issues and PRs.
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632
