### ISSUE TITLE
Change module name to  github.com/kubernetes-sigs/go-open-service-broker-client/v2

### ISSUE THREAD

**Issue by mackwong** [kubernetes-sigs/go-open-service-broker-client#169]
The current mod file is：

```
module sigs.k8s.io/go-open-service-broker-client/v2

go 1.14

require k8s.io/klog/v2 v2.0.0
```

**Comment by jhvhs** [comment]
Thanks for reaching out, @mackwong . Are you experiencing a particular issue?
`sigs.k8s.io` is redirected appropriately, and seems to be working perfectly with the golang toolchain.
