### ISSUE TITLE
connectivity error messages

### ISSUE THREAD

**Issue by cppforlife** [kubernetes-sigs/go-open-service-broker-client#57]
great library so far, would be nice to improve error message from the client so that users of the client do not need to wrap them in something more user friendy.

current errors received:

- missing config.URL

```
Fetching catalog: Get /v2/catalog: unsupported protocol scheme ""
```

- wrong auth creds

```
Using 'http://10.244.0.2:8080' service broker
ERROR: logging before flag.Parse: I0828 18:52:18.359582   97591 client.go:192] handling failure responses

Fetching catalog: Status: 401; ErrorMessage: <nil>; Description: <nil>; ResponseError: invalid character 'N' looking for beginning of value
```

wdyt?

cc @youreddy

**Comment by pmorie** [comment]
@cppforlife I'm very interested in improving the errors.  Do you have suggestions for how each of these could be improved?

**Comment by pmorie** [comment]
(Thanks for the issue, by the way :))

**Comment by cppforlife** [comment]
may be...

> missing config.URL

`Missing config URL` without any lower lvl calls.

> wrong auth creds

`Unauthorized` based on 40x response (whatever brokers meant to return)
