### ISSUE TITLE
expose http client for underlying client customizations

### ISSUE THREAD

**Issue by cppforlife** [kubernetes-sigs/go-open-service-broker-client#58]
would be nice to expose `http.Client` in a configuration or a custom interface `Do(*Request) (*Response, error)`. can even implement oauth token support via this method. 

thoughts?

cc @youreddy

**Comment by pmorie** [comment]
Hi @cppforlife.  Thanks for the issue.  I think it would be good to expose the client, but I'm not sure that the interface is `Do`, maybe more something like `Decorate` that allows you to manipulate the HTTP request.

WDYT?

**Comment by cppforlife** [comment]
@pmorie i think Do interface would be a bit less coupled to the design of the client. For example setting up all kinds of dialer configurations, wrapping with a retry client, etc are fairly common activities.
