### ISSUE TITLE
Should Originating Identity be sent with Last Operation requests?

### ISSUE THREAD

**Issue by kibbles-n-bytes** [kubernetes-sigs/go-open-service-broker-client#85]
Currently, the `PollLastOperation` and `PollBindingLastOperation` functions send originating identity information in their requests. Is this expected behavior?

**Comment by pmorie** [comment]
@staebler what do you think about this one?

**Comment by staebler** [comment]
When the feature was implemented, the OSB API proposal was unequivocal that the originating identity MUST be included in those requests. Looking at the final revision that made it into the spec, it is ambigious to me whether the originating identity MUST be included. The relevant part of the spec is this.

> For any OSB API request that is the result of an action taken by a platform's user, there MUST be an associated OriginatingIdentity header on that HTTP request.

Is a `PollLastOperation` request a result of an action taken by a platform's user? I could argue that it in many cases it is an indirect result of a provision or deprovision. The more interesting question is whether there are scenarios where a broker could use an originating identity in a meaningful way for a `PollLastOperation` request. Could a broker use the originating identity to reject a `PollLastOperation` request if the supply identity differs from the identity supplied with the original operation request? Could a broker use the originating identity from a `PollLastOperation` request to find the operation?

Are there downsides beyond CPU cycle and network bits to including the originating identity? If not, then I am inclined to include the originating identity.
